//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graficos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TaxiDB : DbContext
    {
        public TaxiDB()
            : base("name=TaxiDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        [DbFunction("TaxiDB", "RankingDeVentasDeTaxis")]
        public virtual IQueryable<RankingDeVentasDeTaxis_Result> RankingDeVentasDeTaxis()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<RankingDeVentasDeTaxis_Result>("[TaxiDB].[RankingDeVentasDeTaxis]()");
        }
    }
}
